// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4-PUNlLN5v1uY-DFqYzrrwi3f4TMmIDc',
    appId: '1:975209295461:web:69b2e4e0239d69d78c608c',
    messagingSenderId: '975209295461',
    projectId: 'barka-app-7eb8b',
    authDomain: 'barka-app-7eb8b.firebaseapp.com',
    storageBucket: 'barka-app-7eb8b.firebasestorage.app',
    measurementId: 'G-JQ3EFPSYM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-prr2VYeND-Wy3feCz-xfKFfSExGEj2o',
    appId: '1:975209295461:android:96b3f48ec3135f828c608c',
    messagingSenderId: '975209295461',
    projectId: 'barka-app-7eb8b',
    storageBucket: 'barka-app-7eb8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnBI2ed696CjbIC06vXKwZKO_ncfp4FUg',
    appId: '1:975209295461:ios:6e4e67173be717308c608c',
    messagingSenderId: '975209295461',
    projectId: 'barka-app-7eb8b',
    storageBucket: 'barka-app-7eb8b.firebasestorage.app',
    iosBundleId: 'com.example.barkaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnBI2ed696CjbIC06vXKwZKO_ncfp4FUg',
    appId: '1:975209295461:ios:6e4e67173be717308c608c',
    messagingSenderId: '975209295461',
    projectId: 'barka-app-7eb8b',
    storageBucket: 'barka-app-7eb8b.firebasestorage.app',
    iosBundleId: 'com.example.barkaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4-PUNlLN5v1uY-DFqYzrrwi3f4TMmIDc',
    appId: '1:975209295461:web:90da43d281fcf7528c608c',
    messagingSenderId: '975209295461',
    projectId: 'barka-app-7eb8b',
    authDomain: 'barka-app-7eb8b.firebaseapp.com',
    storageBucket: 'barka-app-7eb8b.firebasestorage.app',
    measurementId: 'G-RM8SS4DHW0',
  );

}